[tasks.all]
dependencies = [
  "toolset",
  "demo-emulator",
]

[tasks.toolset]
dependencies = [
  "build",
  "toolset-cleanup",
  "toolset-produce",
  "build-compiler-capi",
  "build-vm-capi",
  "build-dotnet-wrapper",
  "toolset-post-produce",
  "unity-package",
  "archive-toolset",
]

[tasks.build]
dependencies = [
  "build-debug",
  "build-release",
]

[tasks.build-debug]
command = "cargo"
args = [
  "build",
  "--all",
]

[tasks.build-release]
command = "cargo"
args = [
  "build",
  "--all",
  "--release",
]

[tasks.build-compiler-capi-h]
command = "cbindgen"
args = [
  "kaiju-compiler-capi",
  "-l",
  "c",
  "-o",
  "toolset/include/kaiju_compiler_capi.h",
]

[tasks.build-compiler-capi-hpp]
command = "cbindgen"
args = [
  "kaiju-compiler-capi",
  "-l",
  "c++",
  "-o",
  "toolset/include/kaiju_compiler_capi.hpp",
]

[tasks.build-compiler-capi]
dependencies = [
  "build-compiler-capi-h",
  "build-compiler-capi-hpp",
]

[tasks.build-vm-capi-h]
command = "cbindgen"
args = [
  "kaiju-vm-capi",
  "-l",
  "c",
  "-o",
  "toolset/include/kaiju_vm_capi.h",
]

[tasks.build-vm-capi-hpp]
command = "cbindgen"
args = [
  "kaiju-vm-capi",
  "-l",
  "c++",
  "-o",
  "toolset/include/kaiju_vm_capi.hpp",
]

[tasks.build-vm-capi]
dependencies = [
  "build-vm-capi-h",
  "build-vm-capi-hpp",
]

[tasks.build-dotnet-wrapper]
dependencies = [
  "build-dotnet-wrapper-debug",
  "build-dotnet-wrapper-release",
]

[tasks.build-dotnet-wrapper-debug]
script = [
  "$MSBUILD_BIN ./dotnet/Kaiju.NET.sln /t:Build /p:Configuration=Debug"
]

[tasks.build-dotnet-wrapper-debug.windows]
script = [
  "%MSBUILD_BIN% ./dotnet/Kaiju.NET.sln /t:Build /p:Configuration=Debug"
]

[tasks.build-dotnet-wrapper-release]
script = [
  "$MSBUILD_BIN ./dotnet/Kaiju.NET.sln /t:Build /p:Configuration=Release"
]

[tasks.build-dotnet-wrapper-release.windows]
script = [
  "%MSBUILD_BIN% ./dotnet/Kaiju.NET.sln /t:Build /p:Configuration=Release"
]

[tasks.toolset-cleanup]
script = [
  '''
  echo "* cleanup toolset"
  rm -rf toolset
  mkdir -p toolset/bin
  mkdir -p toolset/lib
  mkdir -p toolset/lib/debug
  mkdir -p toolset/lib/release
  mkdir -p toolset/include
  '''
]

[tasks.toolset-cleanup.windows]
script = [
  '''
  echo "* cleanup toolset"
  rmdir /s /q "%CD%"\toolset
  mkdir "%CD%"\toolset\bin
  mkdir "%CD%"\toolset\lib
  mkdir "%CD%"\toolset\lib\debug
  mkdir "%CD%"\toolset\lib\release
  mkdir "%CD%"\toolset\include
  '''
]

[tasks.toolset-produce]
script = [
  '''
  echo "* produce toolset"
  cp target/release/ckaiju toolset/bin/ckaiju
  cp target/debug/ckaiju toolset/bin/ckaiju-d
  cp target/release/keijo toolset/bin/keijo
  cp target/debug/keijo toolset/bin/keijo-d
  cp target/debug/kaiju_compiler_capi.a toolset/lib/debug/kaiju_compiler_capi.a
  cp target/debug/kaiju_compiler_capi.so toolset/lib/debug/kaiju_compiler_capi.so
  cp target/debug/kaiju_compiler_capi.so.a toolset/lib/debug/kaiju_compiler_capi.so.a
  cp target/release/kaiju_compiler_capi.a toolset/lib/release/kaiju_compiler_capi.a
  cp target/release/kaiju_compiler_capi.so toolset/lib/release/kaiju_compiler_capi.so
  cp target/release/kaiju_compiler_capi.so.a toolset/lib/release/kaiju_compiler_capi.so.a
  cp target/debug/kaiju_vm_capi.a toolset/lib/debug/kaiju_vm_capi.a
  cp target/debug/kaiju_vm_capi.so toolset/lib/debug/kaiju_vm_capi.so
  cp target/debug/kaiju_vm_capi.so.a toolset/lib/debug/kaiju_vm_capi.so.a
  cp target/release/kaiju_vm_capi.a toolset/lib/release/kaiju_vm_capi.a
  cp target/release/kaiju_vm_capi.so toolset/lib/release/kaiju_vm_capi.so
  cp target/release/kaiju_vm_capi.so.a toolset/lib/release/kaiju_vm_capi.so.a
  '''
]

[tasks.toolset-produce.windows]
script = [
  '''
  echo "* produce toolset"
  copy "%CD%"\target\release\ckaiju.exe "%CD%"\toolset\bin\ckaiju.exe
  copy "%CD%"\target\debug\ckaiju.exe "%CD%"\toolset\bin\ckaiju-d.exe
  copy "%CD%"\target\release\keijo.exe "%CD%"\toolset\bin\keijo.exe
  copy "%CD%"\target\debug\keijo.exe "%CD%"\toolset\bin\keijo-d.exe
  copy "%CD%"\target\debug\kaiju_compiler_capi.lib "%CD%"\toolset\lib\debug\kaiju_compiler_capi.lib
  copy "%CD%"\target\debug\kaiju_compiler_capi.dll "%CD%"\toolset\lib\debug\kaiju_compiler_capi.dll
  copy "%CD%"\target\debug\kaiju_compiler_capi.dll.lib "%CD%"\toolset\lib\debug\kaiju_compiler_capi.dll.lib
  copy "%CD%"\target\release\kaiju_compiler_capi.lib "%CD%"\toolset\lib\release\kaiju_compiler_capi.lib
  copy "%CD%"\target\release\kaiju_compiler_capi.dll "%CD%"\toolset\lib\release\kaiju_compiler_capi.dll
  copy "%CD%"\target\release\kaiju_compiler_capi.dll.lib "%CD%"\toolset\lib\release\kaiju_compiler_capi.dll.lib
  copy "%CD%"\target\debug\kaiju_vm_capi.lib "%CD%"\toolset\lib\debug\kaiju_vm_capi.lib
  copy "%CD%"\target\debug\kaiju_vm_capi.dll "%CD%"\toolset\lib\debug\kaiju_vm_capi.dll
  copy "%CD%"\target\debug\kaiju_vm_capi.dll.lib "%CD%"\toolset\lib\debug\kaiju_vm_capi.dll.lib
  copy "%CD%"\target\release\kaiju_vm_capi.lib "%CD%"\toolset\lib\release\kaiju_vm_capi.lib
  copy "%CD%"\target\release\kaiju_vm_capi.dll "%CD%"\toolset\lib\release\kaiju_vm_capi.dll
  copy "%CD%"\target\release\kaiju_vm_capi.dll.lib "%CD%"\toolset\lib\release\kaiju_vm_capi.dll.lib
  '''
]

[tasks.toolset-post-produce]
script = [
  '''
  echo "* post produce toolset"
  cp -r dotnet/Kaiju.Compiler.NET/bin/Debug/netstandard2.0 toolset/lib/debug/
  cp -r dotnet/Kaiju.Compiler.NET/bin/Release/netstandard2.0 toolset/lib/release/
  cp -r dotnet/Kaiju.VirtualMachine.NET/bin/Debug/netstandard2.0 toolset/lib/debug/
  cp -r dotnet/Kaiju.VirtualMachine.NET/bin/Release/netstandard2.0 toolset/lib/release/
  '''
]

[tasks.toolset-post-produce.windows]
script = [
  '''
  echo "* post produce toolset"
  xcopy "%CD%"\dotnet\Kaiju.Compiler.NET\bin\Debug\netstandard2.0 "%CD%"\toolset\lib\debug\
  xcopy "%CD%"\dotnet\Kaiju.Compiler.NET\bin\Release\netstandard2.0 "%CD%"\toolset\lib\release\
  xcopy "%CD%"\dotnet\Kaiju.VirtualMachine.NET\bin\Debug\netstandard2.0 "%CD%"\toolset\lib\debug\
  xcopy "%CD%"\dotnet\Kaiju.VirtualMachine.NET\bin\Release\netstandard2.0 "%CD%"\toolset\lib\release\
  '''
]

[tasks.unity-package]
dependencies = [
  "update-unity-dependencies",
  "build-unity-package",
]

[tasks.update-unity-dependencies]
script = [
  '''
  echo "* update unity dependencies"
  cp -f target/release/kaiju_compiler_capi.so unity/Kaiju.Unity/Assets/Kaiju/Plugins/kaiju_compiler_capi.so
  cp -f target/release/kaiju_vm_capi.so unity/Kaiju.Unity/Assets/Kaiju/Plugins/kaiju_vm_capi.so
  cp -f dotnet/Kaiju.Compiler.NET/bin/Release/netstandard2.0/Kaiju.Compiler.NET.dll unity/Kaiju.Unity/Assets/Kaiju/Plugins/Kaiju.Compiler.NET.dll
  cp -f dotnet/Kaiju.VirtualMachine.NET/bin/Release/netstandard2.0/Kaiju.VirtualMachine.NET.dll unity/Kaiju.Unity/Assets/Kaiju/Plugins/Kaiju.VirtualMachine.NET.dll
  '''
]

[tasks.update-unity-dependencies.windows]
script = [
  '''
  echo "* update unity dependencies"
  copy "%CD%"\target\release\kaiju_compiler_capi.dll "%CD%"\unity\Kaiju.Unity\Assets\Kaiju\Plugins\kaiju_compiler_capi.dll
  copy "%CD%"\target\release\kaiju_vm_capi.dll "%CD%"\unity\Kaiju.Unity\Assets\Kaiju\Plugins\kaiju_vm_capi.dll
  copy "%CD%"\dotnet\Kaiju.Compiler.NET\bin\Release\netstandard2.0\Kaiju.Compiler.NET.dll "%CD%"\unity\Kaiju.Unity\Assets\Kaiju\Plugins\Kaiju.Compiler.NET.dll
  copy "%CD%"\dotnet\Kaiju.VirtualMachine.NET\bin\Release\netstandard2.0\Kaiju.VirtualMachine.NET.dll "%CD%"\unity\Kaiju.Unity\Assets\Kaiju\Plugins\Kaiju.VirtualMachine.NET.dll
  '''
]

[tasks.build-unity-package]
script = [
  '''$UNITY_BIN -projectPath "unity/Kaiju.Unity/" -quit -batchmode -exportPackage Assets/Kaiju ../../toolset/kaiju.unitypackage'''
]

[tasks.build-unity-package.windows]
script = [
  '''%UNITY_BIN% -projectPath "%CD%\unity\Kaiju.Unity\" -quit -batchmode -exportPackage Assets\Kaiju ..\..\toolset\kaiju.unitypackage'''
]

[tasks.demo-emulator]
dependencies = [
  "build-demo-emulator",
  "demo-cleanup",
  "produce-demo-emulator",
  "archive-demo-emulator",
]

[tasks.build-demo-emulator]
dependencies = [
  "build-demo-emulator-debug",
  "build-demo-emulator-release",
]

[tasks.build-demo-emulator-debug]
command = "cargo"
args = [
  "build",
  "--manifest-path",
  "demo-emulator/Cargo.toml",
]

[tasks.build-demo-emulator-release]
command = "cargo"
args = [
  "build",
  "--manifest-path",
  "demo-emulator/Cargo.toml",
  "--release",
]

[tasks.demo-cleanup]
script = [
  '''
  echo "* cleanup demo"
  rm -rf demo
  mkdir -p demo
  mkdir -p demo/res
  '''
]

[tasks.demo-cleanup.windows]
script = [
  '''
  echo "* cleanup demo"
  rmdir /s /q "%CD%"\demo
  mkdir "%CD%"\demo
  mkdir "%CD%"\demo\res
  '''
]

[tasks.produce-demo-emulator]
script = [
  '''
  echo "* produce demo"
  cp demo-emulator/target/release/cartridge demo/cartridge
  cp demo-emulator/target/debug/cartridge demo/cartridge-d
  cp demo-emulator/target/release/console demo/console
  cp demo-emulator/target/debug/console demo/console-d
  cp demo-emulator/target/release/fontgen demo/fontgen
  cp demo-emulator/target/debug/fontgen demo/fontgen-d
  cp -r demo-emulator/res demo/res/
  cp demo-emulator/scripts/run.sh demo/run.sh
  '''
]

[tasks.produce-demo-emulator.windows]
script = [
  '''
  echo "* produce demo"
  copy "%CD%"\demo-emulator\target\release\cartridge.exe "%CD%"\demo\cartridge.exe
  copy "%CD%"\demo-emulator\target\debug\cartridge.exe "%CD%"\demo\cartridge-d.exe
  copy "%CD%"\demo-emulator\target\release\console.exe "%CD%"\demo\console.exe
  copy "%CD%"\demo-emulator\target\debug\console.exe "%CD%"\demo\console-d.exe
  copy "%CD%"\demo-emulator\target\release\fontgen.exe "%CD%"\demo\fontgen.exe
  copy "%CD%"\demo-emulator\target\debug\fontgen.exe "%CD%"\demo\fontgen-d.exe
  xcopy "%CD%"\demo-emulator\res "%CD%"\demo\res\
  copy "%CD%"\demo-emulator\scripts\run.bat "%CD%"\demo\run.bat
  '''
]

[tasks.archive-toolset]
script = [
  '''$SEVENZIP_BIN a -tzip toolset/kaiju-toolset-${KAIJU_VERSION}-lin64.zip toolset/*'''
]

[tasks.archive-toolset.windows]
script = [
  '''%SEVENZIP_BIN% a -tzip "%CD%\toolset\kaiju-toolset-%KAIJU_VERSION%-win64.zip" "%CD%\toolset\*"'''
]

[tasks.archive-demo-emulator]
script = [
  '''$SEVENZIP_BIN a -tzip demo/demo-emulator-${KAIJU_VERSION}-lin64.zip demo/*'''
]

[tasks.archive-demo-emulator.windows]
script = [
  '''%SEVENZIP_BIN% a -tzip "%CD%\demo\demo-emulator-%KAIJU_VERSION%-win64.zip" "%CD%\demo\*"'''
]
